// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MauiApp1.Model;
//
//    var course = Course.FromJson(jsonString);

namespace MauiApp1.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Course
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }
    }

    public partial class Course
    {
        public static List<Course> FromJson(string json) => JsonConvert.DeserializeObject<List<Course>>(json, MauiApp1.Model.Converter.Settings);
    }

    public static class CourseSerialize
    {
        public static string ToJson(this List<Course> self) => JsonConvert.SerializeObject(self, MauiApp1.Model.Converter.Settings);
    }

    internal static class CourseConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
